### PR TITLE
Propose a new NodeJS file to act as the main node server for the backend

### PR DESCRIPTION
**Pull request by semiangel**
- Propose a new NodeJS file to act as the main node server for the backend.
- Moved unused solidity files into a folder.

### CODE REVIEW

**Comment by krittakondev** [comment]
Can you please add the package.json file as well?

**Comment by semiangel** [comment]
> Can you please add the package.json file as well?

Will do!

**Comment by semiangel** [comment]
Just committed the file and its node packages in the forked, does it appear here?

> > Can you please add the package.json file as well?
> 
> Will do!

**Comment by semiangel** [comment]
- Please note that the nodeServer.js file was quickly generated using ChatGPT for easy code outline. 
- Didn't properly test it yet. 
- May need to properly set up the MongoDB database and adjust some parameters in the code first to make it work!

**Comment by krittakondev** [comment]
don't need add folder node_modules/

**Comment by semiangel** [comment]
let see if node_modules/ disappeared

**Comment by krittakondev** [comment]
> let see if node_modules/ disappeared

yes

**Comment by semiangel** [comment]
ใครก็ได้ merge ให้ทีจ้า

**Review by pleaseworkibegyou — APPROVED** [review]

**Pull request merged**
